"""
StructureAnalyzer – high-level orchestrator that runs all analyzers
and produces a suggested JSON config template for an unknown PLC format.
"""

from .pattern_detector import PatternDetector, PatternResult
from .timestamp_detector import TimestampDetector, DetectedTimestamp
from utils.logger import AppLogger

log = AppLogger()


class StructureAnalyzer:
    """
    Combines PatternDetector and TimestampDetector to auto-generate
    a parsing config suggestion for unknown PLC data.
    """

    def __init__(self):
        self._pattern_det = PatternDetector()
        self._ts_det = TimestampDetector()

    def analyze(self, hex_data: str) -> dict:
        """
        Fully analyze hex_data and return a dict containing:
          - pattern_result: PatternResult
          - timestamps: list[DetectedTimestamp]
          - suggested_config: dict (auto-generated JSON template)
          - summary: str (human-readable summary)
        """
        log.info("StructureAnalyzer: starting analysis...")

        pattern_result: PatternResult = self._pattern_det.analyze(hex_data)
        timestamps: list[DetectedTimestamp] = self._ts_det.detect_all(hex_data)
        period_from_ts = self._ts_det.detect_period(timestamps)

        # Reconcile period
        period = period_from_ts or pattern_result.detected_period

        suggested_config = self._build_suggested_config(
            pattern_result, timestamps, period
        )

        summary_lines = [
            f"Detected packet period: {period} words ({(period or 0) * 2} bytes)",
            f"Timestamps found: {len(timestamps)}",
        ]
        summary_lines += pattern_result.suggestions
        for pf in pattern_result.probable_fields[:10]:
            summary_lines.append(
                f"  Word {pf['word_offset']:3d} (byte {pf['byte_offset']:3d}): "
                f"{pf['label']} (conf={pf['confidence']:.0%}, "
                f"range={pf['min']}–{pf['max']}, unique={pf['unique_count']})"
            )

        return {
            "pattern_result": pattern_result,
            "timestamps": timestamps,
            "period_words": period,
            "suggested_config": suggested_config,
            "summary": "\n".join(summary_lines),
        }

    # ------------------------------------------------------------------
    # Config template builder
    # ------------------------------------------------------------------

    def _build_suggested_config(
        self,
        pattern: PatternResult,
        timestamps: list[DetectedTimestamp],
        period: int | None,
    ) -> dict:
        """Build a JSON-ready dict that can be saved and used as a parser config."""
        fields = []

        # Add fields from detected probable fields
        field_type_map = {
            "year": ("year", "uint16"),
            "month": ("month", "uint16"),
            "day": ("day", "uint16"),
            "hour": ("hour", "uint16"),
            "minute/second": ("minute", "uint16"),
            "millisecond?": ("millisecond", "uint16"),
            "sensor_register": ("sensor", "uint16"),
        }

        used_offsets = set()
        for pf in pattern.probable_fields:
            label = pf.get("label", "")
            conf = pf.get("confidence", 0)
            word_offset = pf.get("word_offset", 0)
            if conf < 0.4 or word_offset in used_offsets:
                continue
            for key, (fname, dtype) in field_type_map.items():
                if key in label:
                    fields.append({
                        "name": f"{fname}_{word_offset}" if fname == "sensor" else fname,
                        "word_offset": word_offset,
                        "size_words": 1,
                        "byteorder": "big",
                        "signed": False,
                        "data_type": dtype,
                        "description": f"Auto-detected: {label} (conf={conf:.0%})",
                        "register": f"D{word_offset * 10}",
                    })
                    used_offsets.add(word_offset)
                    break

        # Timestamp offset from first detected timestamp
        ts_word_offset = timestamps[0].word_offset if timestamps else 0

        config = {
            "_comment": "Auto-generated by StructureAnalyzer — review and adjust before use.",
            "format_name": "auto_detected",
            "protocol": "unknown",
            "endianness": "big",
            "packet_definition": {
                "packet_size_bytes": (period or 20) * 2,
                "header_size_bytes": 0,
                "start_markers": [],
            },
            "timestamp": {
                "word_offset": ts_word_offset,
                "fields": ["year", "month", "day", "hour", "minute", "second"],
            },
            "fields": fields,
            "parser_options": {
                "skip_padding": True,
                "min_valid_bytes": 4,
                "validate_timestamps": True,
            },
        }

        return config
